### ISSUE TITLE
pochemu_iskusstvo_postmoderna_takaya_huynya

### ISSUE THREAD

**Issue by meowmeansmeow** [ezome/test#1]
если вкратце, то на перспективу познающего/страдающего/наслаждающегося субъекта налезают рилсы. memento дохуя пожалуйста — занимайтесь настоящим трудом, который есть всегда нечто иррациональное и поэтому состоящее из нервной, чувственной материи.

**Comment by ezome** [comment]
> memento дохуя пожалуйста — занимайтесь настоящим трудом, который есть всегда нечто иррациональное и поэтому состоящее из нервной, чувственной материи.

харашо зо-в—падали, можно скозать, впаяли non-reels. НО ВЫ ЗНАЛИ, что ПСИХЕЯ ПИТАЕТЦА мирмицинами? 

| Заголовок |
|--------|
| Клетка |
